apiVersion: v1
kind: Namespace
metadata:
  name: npm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: npm
  namespace: npm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: npm
  template:
    metadata:
      labels:
        app: npm
    spec:
      containers:
      - name: npm
        image: jc21/nginx-proxy-manager:latest
        ports:
        - containerPort: 80
        - containerPort: 81
        - containerPort: 443
        volumeMounts:
        - name: data
          mountPath: /data
        - name: letsencrypt
          mountPath: /etc/letsencrypt
      volumes:
      - name: data
        hostPath:
          path: /var/lib/npm/data
      - name: letsencrypt
        hostPath:
          path: /var/lib/npm/letsencrypt
---
apiVersion: v1
kind: Service
metadata:
  name: npm-service
  namespace: npm
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: admin
    port: 81
    targetPort: 81
  - name: https
    port: 443
    targetPort: 443
  selector:
    app: npm


